
(define (problem example-problem)
  (:domain htg-child-snack)
  (:objects
    child0 child1 child2 child3 child4 child5 child6 - child
    bread0 bread1 bread2 bread3 bread4 bread5 bread6 - bread-portion
    content-0 content-1 content-2 content-3 - content-description
    content-0-0 content-0-1 content-0-2 content-0-3 content-0-4 content-0-5 content-0-6 content-0-7 content-0-8 content-0-9 content-0-10 content-0-11 content-0-12 content-0-13 content-0-14 content-0-15 content-0-16 content-0-17 content-0-18 content-0-19 content-0-20 content-0-21 content-0-22 content-0-23 content-0-24 content-0-25 content-0-26 content-0-27 content-0-28 content-0-29 content-0-30 content-0-31 content-0-32 content-0-33 content-0-34 content-0-35 content-0-36 content-0-37 content-0-38 - content-portion
    content-1-0 content-1-1 content-1-2 content-1-3 content-1-4 content-1-5 content-1-6 content-1-7 content-1-8 content-1-9 content-1-10 content-1-11 content-1-12 content-1-13 content-1-14 content-1-15 content-1-16 content-1-17 content-1-18 content-1-19 content-1-20 content-1-21 content-1-22 content-1-23 content-1-24 content-1-25 content-1-26 content-1-27 content-1-28 content-1-29 content-1-30 content-1-31 content-1-32 content-1-33 content-1-34 content-1-35 content-1-36 content-1-37 content-1-38 content-1-39 content-1-40 content-1-41 content-1-42 content-1-43 content-1-44 content-1-45 content-1-46 - content-portion
    content-2-0 content-2-1 content-2-2 content-2-3 content-2-4 content-2-5 content-2-6 content-2-7 content-2-8 content-2-9 content-2-10 content-2-11 content-2-12 content-2-13 content-2-14 content-2-15 content-2-16 content-2-17 content-2-18 content-2-19 content-2-20 content-2-21 content-2-22 content-2-23 content-2-24 content-2-25 content-2-26 content-2-27 content-2-28 content-2-29 content-2-30 content-2-31 content-2-32 content-2-33 - content-portion
    content-3-0 content-3-1 content-3-2 content-3-3 content-3-4 content-3-5 content-3-6 content-3-7 content-3-8 content-3-9 content-3-10 content-3-11 content-3-12 content-3-13 content-3-14 content-3-15 content-3-16 content-3-17 content-3-18 content-3-19 content-3-20 content-3-21 content-3-22 content-3-23 content-3-24 content-3-25 content-3-26 content-3-27 content-3-28 content-3-29 content-3-30 content-3-31 content-3-32 content-3-33 - content-portion
    tray0 tray1 tray2 - tray
    table0 table1 table2 table3 table4 - place
    sandw0 sandw1 sandw2 sandw3 sandw4 sandw5 sandw6 - sandwich
  )
  (:init
     ;; everythin starts in the kitchen
     (at tray0 kitchen)
     (at tray1 kitchen)
     (at tray2 kitchen)
			    (at_kitchen_bread bread0)
			    (at_kitchen_bread bread1)
			    (at_kitchen_bread bread2)
			    (at_kitchen_bread bread3)
			    (at_kitchen_bread bread4)
			    (at_kitchen_bread bread5)
			    (at_kitchen_bread bread6)
			    (at_kitchen_content content-0-0)
			    (at_kitchen_content content-0-1)
			    (at_kitchen_content content-0-2)
			    (at_kitchen_content content-0-3)
			    (at_kitchen_content content-0-4)
			    (at_kitchen_content content-0-5)
			    (at_kitchen_content content-0-6)
			    (at_kitchen_content content-0-7)
			    (at_kitchen_content content-0-8)
			    (at_kitchen_content content-0-9)
			    (at_kitchen_content content-0-10)
			    (at_kitchen_content content-0-11)
			    (at_kitchen_content content-0-12)
			    (at_kitchen_content content-0-13)
			    (at_kitchen_content content-0-14)
			    (at_kitchen_content content-0-15)
			    (at_kitchen_content content-0-16)
			    (at_kitchen_content content-0-17)
			    (at_kitchen_content content-0-18)
			    (at_kitchen_content content-0-19)
			    (at_kitchen_content content-0-20)
			    (at_kitchen_content content-0-21)
			    (at_kitchen_content content-0-22)
			    (at_kitchen_content content-0-23)
			    (at_kitchen_content content-0-24)
			    (at_kitchen_content content-0-25)
			    (at_kitchen_content content-0-26)
			    (at_kitchen_content content-0-27)
			    (at_kitchen_content content-0-28)
			    (at_kitchen_content content-0-29)
			    (at_kitchen_content content-0-30)
			    (at_kitchen_content content-0-31)
			    (at_kitchen_content content-0-32)
			    (at_kitchen_content content-0-33)
			    (at_kitchen_content content-0-34)
			    (at_kitchen_content content-0-35)
			    (at_kitchen_content content-0-36)
			    (at_kitchen_content content-0-37)
			    (at_kitchen_content content-0-38)
			    (at_kitchen_content content-1-0)
			    (at_kitchen_content content-1-1)
			    (at_kitchen_content content-1-2)
			    (at_kitchen_content content-1-3)
			    (at_kitchen_content content-1-4)
			    (at_kitchen_content content-1-5)
			    (at_kitchen_content content-1-6)
			    (at_kitchen_content content-1-7)
			    (at_kitchen_content content-1-8)
			    (at_kitchen_content content-1-9)
			    (at_kitchen_content content-1-10)
			    (at_kitchen_content content-1-11)
			    (at_kitchen_content content-1-12)
			    (at_kitchen_content content-1-13)
			    (at_kitchen_content content-1-14)
			    (at_kitchen_content content-1-15)
			    (at_kitchen_content content-1-16)
			    (at_kitchen_content content-1-17)
			    (at_kitchen_content content-1-18)
			    (at_kitchen_content content-1-19)
			    (at_kitchen_content content-1-20)
			    (at_kitchen_content content-1-21)
			    (at_kitchen_content content-1-22)
			    (at_kitchen_content content-1-23)
			    (at_kitchen_content content-1-24)
			    (at_kitchen_content content-1-25)
			    (at_kitchen_content content-1-26)
			    (at_kitchen_content content-1-27)
			    (at_kitchen_content content-1-28)
			    (at_kitchen_content content-1-29)
			    (at_kitchen_content content-1-30)
			    (at_kitchen_content content-1-31)
			    (at_kitchen_content content-1-32)
			    (at_kitchen_content content-1-33)
			    (at_kitchen_content content-1-34)
			    (at_kitchen_content content-1-35)
			    (at_kitchen_content content-1-36)
			    (at_kitchen_content content-1-37)
			    (at_kitchen_content content-1-38)
			    (at_kitchen_content content-1-39)
			    (at_kitchen_content content-1-40)
			    (at_kitchen_content content-1-41)
			    (at_kitchen_content content-1-42)
			    (at_kitchen_content content-1-43)
			    (at_kitchen_content content-1-44)
			    (at_kitchen_content content-1-45)
			    (at_kitchen_content content-1-46)
			    (at_kitchen_content content-2-0)
			    (at_kitchen_content content-2-1)
			    (at_kitchen_content content-2-2)
			    (at_kitchen_content content-2-3)
			    (at_kitchen_content content-2-4)
			    (at_kitchen_content content-2-5)
			    (at_kitchen_content content-2-6)
			    (at_kitchen_content content-2-7)
			    (at_kitchen_content content-2-8)
			    (at_kitchen_content content-2-9)
			    (at_kitchen_content content-2-10)
			    (at_kitchen_content content-2-11)
			    (at_kitchen_content content-2-12)
			    (at_kitchen_content content-2-13)
			    (at_kitchen_content content-2-14)
			    (at_kitchen_content content-2-15)
			    (at_kitchen_content content-2-16)
			    (at_kitchen_content content-2-17)
			    (at_kitchen_content content-2-18)
			    (at_kitchen_content content-2-19)
			    (at_kitchen_content content-2-20)
			    (at_kitchen_content content-2-21)
			    (at_kitchen_content content-2-22)
			    (at_kitchen_content content-2-23)
			    (at_kitchen_content content-2-24)
			    (at_kitchen_content content-2-25)
			    (at_kitchen_content content-2-26)
			    (at_kitchen_content content-2-27)
			    (at_kitchen_content content-2-28)
			    (at_kitchen_content content-2-29)
			    (at_kitchen_content content-2-30)
			    (at_kitchen_content content-2-31)
			    (at_kitchen_content content-2-32)
			    (at_kitchen_content content-2-33)
			    (at_kitchen_content content-3-0)
			    (at_kitchen_content content-3-1)
			    (at_kitchen_content content-3-2)
			    (at_kitchen_content content-3-3)
			    (at_kitchen_content content-3-4)
			    (at_kitchen_content content-3-5)
			    (at_kitchen_content content-3-6)
			    (at_kitchen_content content-3-7)
			    (at_kitchen_content content-3-8)
			    (at_kitchen_content content-3-9)
			    (at_kitchen_content content-3-10)
			    (at_kitchen_content content-3-11)
			    (at_kitchen_content content-3-12)
			    (at_kitchen_content content-3-13)
			    (at_kitchen_content content-3-14)
			    (at_kitchen_content content-3-15)
			    (at_kitchen_content content-3-16)
			    (at_kitchen_content content-3-17)
			    (at_kitchen_content content-3-18)
			    (at_kitchen_content content-3-19)
			    (at_kitchen_content content-3-20)
			    (at_kitchen_content content-3-21)
			    (at_kitchen_content content-3-22)
			    (at_kitchen_content content-3-23)
			    (at_kitchen_content content-3-24)
			    (at_kitchen_content content-3-25)
			    (at_kitchen_content content-3-26)
			    (at_kitchen_content content-3-27)
			    (at_kitchen_content content-3-28)
			    (at_kitchen_content content-3-29)
			    (at_kitchen_content content-3-30)
			    (at_kitchen_content content-3-31)
			    (at_kitchen_content content-3-32)
			    (at_kitchen_content content-3-33) 

     ;; content descriptions
                (descr content-0-0 content-0)
                (descr content-0-1 content-0)
                (descr content-0-2 content-0)
                (descr content-0-3 content-0)
                (descr content-0-4 content-0)
                (descr content-0-5 content-0)
                (descr content-0-6 content-0)
                (descr content-0-7 content-0)
                (descr content-0-8 content-0)
                (descr content-0-9 content-0)
                (descr content-0-10 content-0)
                (descr content-0-11 content-0)
                (descr content-0-12 content-0)
                (descr content-0-13 content-0)
                (descr content-0-14 content-0)
                (descr content-0-15 content-0)
                (descr content-0-16 content-0)
                (descr content-0-17 content-0)
                (descr content-0-18 content-0)
                (descr content-0-19 content-0)
                (descr content-0-20 content-0)
                (descr content-0-21 content-0)
                (descr content-0-22 content-0)
                (descr content-0-23 content-0)
                (descr content-0-24 content-0)
                (descr content-0-25 content-0)
                (descr content-0-26 content-0)
                (descr content-0-27 content-0)
                (descr content-0-28 content-0)
                (descr content-0-29 content-0)
                (descr content-0-30 content-0)
                (descr content-0-31 content-0)
                (descr content-0-32 content-0)
                (descr content-0-33 content-0)
                (descr content-0-34 content-0)
                (descr content-0-35 content-0)
                (descr content-0-36 content-0)
                (descr content-0-37 content-0)
                (descr content-0-38 content-0)
                (descr content-1-0 content-1)
                (descr content-1-1 content-1)
                (descr content-1-2 content-1)
                (descr content-1-3 content-1)
                (descr content-1-4 content-1)
                (descr content-1-5 content-1)
                (descr content-1-6 content-1)
                (descr content-1-7 content-1)
                (descr content-1-8 content-1)
                (descr content-1-9 content-1)
                (descr content-1-10 content-1)
                (descr content-1-11 content-1)
                (descr content-1-12 content-1)
                (descr content-1-13 content-1)
                (descr content-1-14 content-1)
                (descr content-1-15 content-1)
                (descr content-1-16 content-1)
                (descr content-1-17 content-1)
                (descr content-1-18 content-1)
                (descr content-1-19 content-1)
                (descr content-1-20 content-1)
                (descr content-1-21 content-1)
                (descr content-1-22 content-1)
                (descr content-1-23 content-1)
                (descr content-1-24 content-1)
                (descr content-1-25 content-1)
                (descr content-1-26 content-1)
                (descr content-1-27 content-1)
                (descr content-1-28 content-1)
                (descr content-1-29 content-1)
                (descr content-1-30 content-1)
                (descr content-1-31 content-1)
                (descr content-1-32 content-1)
                (descr content-1-33 content-1)
                (descr content-1-34 content-1)
                (descr content-1-35 content-1)
                (descr content-1-36 content-1)
                (descr content-1-37 content-1)
                (descr content-1-38 content-1)
                (descr content-1-39 content-1)
                (descr content-1-40 content-1)
                (descr content-1-41 content-1)
                (descr content-1-42 content-1)
                (descr content-1-43 content-1)
                (descr content-1-44 content-1)
                (descr content-1-45 content-1)
                (descr content-1-46 content-1)
                (descr content-2-0 content-2)
                (descr content-2-1 content-2)
                (descr content-2-2 content-2)
                (descr content-2-3 content-2)
                (descr content-2-4 content-2)
                (descr content-2-5 content-2)
                (descr content-2-6 content-2)
                (descr content-2-7 content-2)
                (descr content-2-8 content-2)
                (descr content-2-9 content-2)
                (descr content-2-10 content-2)
                (descr content-2-11 content-2)
                (descr content-2-12 content-2)
                (descr content-2-13 content-2)
                (descr content-2-14 content-2)
                (descr content-2-15 content-2)
                (descr content-2-16 content-2)
                (descr content-2-17 content-2)
                (descr content-2-18 content-2)
                (descr content-2-19 content-2)
                (descr content-2-20 content-2)
                (descr content-2-21 content-2)
                (descr content-2-22 content-2)
                (descr content-2-23 content-2)
                (descr content-2-24 content-2)
                (descr content-2-25 content-2)
                (descr content-2-26 content-2)
                (descr content-2-27 content-2)
                (descr content-2-28 content-2)
                (descr content-2-29 content-2)
                (descr content-2-30 content-2)
                (descr content-2-31 content-2)
                (descr content-2-32 content-2)
                (descr content-2-33 content-2)
                (descr content-3-0 content-3)
                (descr content-3-1 content-3)
                (descr content-3-2 content-3)
                (descr content-3-3 content-3)
                (descr content-3-4 content-3)
                (descr content-3-5 content-3)
                (descr content-3-6 content-3)
                (descr content-3-7 content-3)
                (descr content-3-8 content-3)
                (descr content-3-9 content-3)
                (descr content-3-10 content-3)
                (descr content-3-11 content-3)
                (descr content-3-12 content-3)
                (descr content-3-13 content-3)
                (descr content-3-14 content-3)
                (descr content-3-15 content-3)
                (descr content-3-16 content-3)
                (descr content-3-17 content-3)
                (descr content-3-18 content-3)
                (descr content-3-19 content-3)
                (descr content-3-20 content-3)
                (descr content-3-21 content-3)
                (descr content-3-22 content-3)
                (descr content-3-23 content-3)
                (descr content-3-24 content-3)
                (descr content-3-25 content-3)
                (descr content-3-26 content-3)
                (descr content-3-27 content-3)
                (descr content-3-28 content-3)
                (descr content-3-29 content-3)
                (descr content-3-30 content-3)
                (descr content-3-31 content-3)
                (descr content-3-32 content-3)
                (descr content-3-33 content-3)
     
     ;; which sandwichs the kids accept
     (likes child4 content-3)
     (likes child0 content-0)
     (likes child0 content-2)
     (likes child0 content-3)
     (likes child6 content-2)
     (likes child6 content-0)
     (likes child3 content-3)
     (likes child4 content-1)
     (likes child6 content-3)
     (likes child5 content-0)
     (likes child5 content-2)
     (likes child3 content-1)
     (likes child2 content-1)
     (likes child4 content-0)
     (likes child4 content-2)
     (likes child2 content-2)
     (likes child2 content-0)
     (likes child1 content-1)
     (likes child2 content-3)
     (likes child6 content-1)
     (likes child3 content-2)
     (likes child3 content-0)
     (likes child1 content-2)
     (likes child1 content-0)
     (likes child5 content-3)
     (likes child1 content-3)
     (likes child0 content-1)
     (likes child5 content-1)

     ;; where children are
     (waiting child0 table0)
     (waiting child1 table1)
     (waiting child2 table2)
     (waiting child3 table3)
     (waiting child4 table4)
     (waiting child5 table0)
     (waiting child6 table1)

     ;;sandwich dummies
     (notexist sandw0)
     (notexist sandw1)
     (notexist sandw2)
     (notexist sandw3)
     (notexist sandw4)
     (notexist sandw5)
     (notexist sandw6)
  )
  (:goal
    (and
     (served child0)
     (served child1)
     (served child2)
     (served child3)
     (served child4)
     (served child5)
     (served child6)
    )
  )
)

