;Copyright 2018 The MITRE Corporation. All rights reserved. Approved for public release. Distribution unlimited 17-2122.
; For more information on CALDERA, the automated adversary emulation system, visit https://github.com/mitre/caldera or email attack@mitre.org
; This has 12 hosts, 1 user, 1 admin per host, 1 active account per host
(define (problem p12_hosts_trial_1)
(:domain caldera)
(:objects id_dsSchtask id_dqSchtask id_dwSchtask id_doSchtask id_dpSchtask id_dzSchtask id_drSchtask id_dxSchtask id_dtSchtask id_dvSchtask id_dySchtask id_duSchtask - ObservedSchtask 
 id_dDomainCredential - ObservedDomainCredential 
 id_cDomainUser - ObservedDomainUser 
 id_aDomain - ObservedDomain 
 num__36 num__43 num__58 num__57 num__37 num__50 num__64 num__65 num__79 num__23 num__85 num__86 num__72 num__71 num__15 num__29 num__16 num__30 num__22 num__8 num__9 num__44 num__78 num__51 - num 
 id_ewRat id_epRat id_eqRat id_emRat id_eoRat id_enRat id_evRat id_etRat id_euRat id_dmRat id_erRat id_exRat id_esRat - ObservedRat 
 id_ebShare id_eaShare id_ecShare id_eiShare id_ekShare id_ehShare id_efShare id_edShare id_ejShare id_elShare id_eeShare id_egShare - ObservedShare 
 id_ckHost id_bbHost id_nHost id_dfHost id_bpHost id_cdHost id_biHost id_crHost id_cyHost id_bwHost id_gHost id_uHost - ObservedHost 
 str__dk str__de str__dn str__cb str__l str__ca str__z str__cp str__dj str__bn str__cj str__ch str__s str__dd str__t str__b str__dl str__james str__ci str__bv str__r str__cq str__bm str__dc str__ba str__e str__f str__bt str__alpha str__y str__m str__cc str__bf str__bg str__co str__cw str__bu str__bh str__cx str__k str__cv str__bo - string 
 id_czTimeDelta id_vTimeDelta id_hTimeDelta id_bjTimeDelta id_bqTimeDelta id_csTimeDelta id_ceTimeDelta id_clTimeDelta id_dgTimeDelta id_oTimeDelta id_bxTimeDelta id_bcTimeDelta - ObservedTimeDelta 
 id_fhFile id_fiFile id_eyFile id_ezFile id_faFile id_feFile id_fjFile id_fcFile id_fgFile id_fdFile id_ffFile id_fbFile - ObservedFile 
)
(:init     (knows id_ckHost)
     (knows id_dmRat)
     (knows_property id_ckHost pfqdn)
     (knows_property id_dmRat pexecutable)
     (knows_property id_dmRat phost)
     (mem_cached_domain_creds id_bbHost id_dDomainCredential)
     (mem_cached_domain_creds id_biHost id_dDomainCredential)
     (mem_cached_domain_creds id_bpHost id_dDomainCredential)
     (mem_cached_domain_creds id_bwHost id_dDomainCredential)
     (mem_cached_domain_creds id_cdHost id_dDomainCredential)
     (mem_cached_domain_creds id_ckHost id_dDomainCredential)
     (mem_cached_domain_creds id_crHost id_dDomainCredential)
     (mem_cached_domain_creds id_cyHost id_dDomainCredential)
     (mem_cached_domain_creds id_dfHost id_dDomainCredential)
     (mem_cached_domain_creds id_gHost id_dDomainCredential)
     (mem_cached_domain_creds id_nHost id_dDomainCredential)
     (mem_cached_domain_creds id_uHost id_dDomainCredential)
     (mem_domain_user_admins id_bbHost id_cDomainUser)
     (mem_domain_user_admins id_biHost id_cDomainUser)
     (mem_domain_user_admins id_bpHost id_cDomainUser)
     (mem_domain_user_admins id_bwHost id_cDomainUser)
     (mem_domain_user_admins id_cdHost id_cDomainUser)
     (mem_domain_user_admins id_ckHost id_cDomainUser)
     (mem_domain_user_admins id_crHost id_cDomainUser)
     (mem_domain_user_admins id_cyHost id_cDomainUser)
     (mem_domain_user_admins id_dfHost id_cDomainUser)
     (mem_domain_user_admins id_gHost id_cDomainUser)
     (mem_domain_user_admins id_nHost id_cDomainUser)
     (mem_domain_user_admins id_uHost id_cDomainUser)
     (mem_hosts id_aDomain id_bbHost)
     (mem_hosts id_aDomain id_biHost)
     (mem_hosts id_aDomain id_bpHost)
     (mem_hosts id_aDomain id_bwHost)
     (mem_hosts id_aDomain id_cdHost)
     (mem_hosts id_aDomain id_ckHost)
     (mem_hosts id_aDomain id_crHost)
     (mem_hosts id_aDomain id_cyHost)
     (mem_hosts id_aDomain id_dfHost)
     (mem_hosts id_aDomain id_gHost)
     (mem_hosts id_aDomain id_nHost)
     (mem_hosts id_aDomain id_uHost)
     (prop_cred id_cDomainUser id_dDomainCredential)
     (prop_dc id_bbHost no)
     (prop_dc id_biHost no)
     (prop_dc id_bpHost no)
     (prop_dc id_bwHost no)
     (prop_dc id_cdHost no)
     (prop_dc id_ckHost no)
     (prop_dc id_crHost no)
     (prop_dc id_cyHost no)
     (prop_dc id_dfHost no)
     (prop_dc id_gHost no)
     (prop_dc id_nHost no)
     (prop_dc id_uHost no)
     (prop_dns_domain id_aDomain str__b)
     (prop_dns_domain_name id_bbHost str__bh)
     (prop_dns_domain_name id_biHost str__bo)
     (prop_dns_domain_name id_bpHost str__bv)
     (prop_dns_domain_name id_bwHost str__cc)
     (prop_dns_domain_name id_cdHost str__cj)
     (prop_dns_domain_name id_ckHost str__cq)
     (prop_dns_domain_name id_crHost str__cx)
     (prop_dns_domain_name id_cyHost str__de)
     (prop_dns_domain_name id_dfHost str__dl)
     (prop_dns_domain_name id_gHost str__m)
     (prop_dns_domain_name id_nHost str__t)
     (prop_dns_domain_name id_uHost str__ba)
     (prop_domain id_bbHost id_aDomain)
     (prop_domain id_biHost id_aDomain)
     (prop_domain id_bpHost id_aDomain)
     (prop_domain id_bwHost id_aDomain)
     (prop_domain id_cDomainUser id_aDomain)
     (prop_domain id_cdHost id_aDomain)
     (prop_domain id_ckHost id_aDomain)
     (prop_domain id_crHost id_aDomain)
     (prop_domain id_cyHost id_aDomain)
     (prop_domain id_dDomainCredential id_aDomain)
     (prop_domain id_dfHost id_aDomain)
     (prop_domain id_gHost id_aDomain)
     (prop_domain id_nHost id_aDomain)
     (prop_domain id_uHost id_aDomain)
     (prop_elevated id_dmRat yes)
     (prop_executable id_dmRat str__dn)
     (prop_fqdn id_bbHost str__bg)
     (prop_fqdn id_biHost str__bn)
     (prop_fqdn id_bpHost str__bu)
     (prop_fqdn id_bwHost str__cb)
     (prop_fqdn id_cdHost str__ci)
     (prop_fqdn id_ckHost str__cp)
     (prop_fqdn id_crHost str__cw)
     (prop_fqdn id_cyHost str__dd)
     (prop_fqdn id_dfHost str__dk)
     (prop_fqdn id_gHost str__l)
     (prop_fqdn id_nHost str__s)
     (prop_fqdn id_uHost str__z)
     (prop_host id_bcTimeDelta id_bbHost)
     (prop_host id_bjTimeDelta id_biHost)
     (prop_host id_bqTimeDelta id_bpHost)
     (prop_host id_bxTimeDelta id_bwHost)
     (prop_host id_ceTimeDelta id_cdHost)
     (prop_host id_clTimeDelta id_ckHost)
     (prop_host id_csTimeDelta id_crHost)
     (prop_host id_czTimeDelta id_cyHost)
     (prop_host id_dgTimeDelta id_dfHost)
     (prop_host id_dmRat id_ckHost)
     (prop_host id_hTimeDelta id_gHost)
     (prop_host id_oTimeDelta id_nHost)
     (prop_host id_vTimeDelta id_uHost)
     (prop_hostname id_bbHost str__bf)
     (prop_hostname id_biHost str__bm)
     (prop_hostname id_bpHost str__bt)
     (prop_hostname id_bwHost str__ca)
     (prop_hostname id_cdHost str__ch)
     (prop_hostname id_ckHost str__co)
     (prop_hostname id_crHost str__cv)
     (prop_hostname id_cyHost str__dc)
     (prop_hostname id_dfHost str__dj)
     (prop_hostname id_gHost str__k)
     (prop_hostname id_nHost str__r)
     (prop_hostname id_uHost str__y)
     (prop_is_group id_cDomainUser no)
     (prop_microseconds id_bcTimeDelta num__29)
     (prop_microseconds id_bjTimeDelta num__36)
     (prop_microseconds id_bqTimeDelta num__43)
     (prop_microseconds id_bxTimeDelta num__50)
     (prop_microseconds id_ceTimeDelta num__57)
     (prop_microseconds id_clTimeDelta num__64)
     (prop_microseconds id_csTimeDelta num__71)
     (prop_microseconds id_czTimeDelta num__78)
     (prop_microseconds id_dgTimeDelta num__85)
     (prop_microseconds id_hTimeDelta num__8)
     (prop_microseconds id_oTimeDelta num__15)
     (prop_microseconds id_vTimeDelta num__22)
     (prop_password id_dDomainCredential str__e)
     (prop_seconds id_bcTimeDelta num__30)
     (prop_seconds id_bjTimeDelta num__37)
     (prop_seconds id_bqTimeDelta num__44)
     (prop_seconds id_bxTimeDelta num__51)
     (prop_seconds id_ceTimeDelta num__58)
     (prop_seconds id_clTimeDelta num__65)
     (prop_seconds id_csTimeDelta num__72)
     (prop_seconds id_czTimeDelta num__79)
     (prop_seconds id_dgTimeDelta num__86)
     (prop_seconds id_hTimeDelta num__9)
     (prop_seconds id_oTimeDelta num__16)
     (prop_seconds id_vTimeDelta num__23)
     (prop_sid id_cDomainUser str__f)
     (prop_timedelta id_bbHost id_bcTimeDelta)
     (prop_timedelta id_biHost id_bjTimeDelta)
     (prop_timedelta id_bpHost id_bqTimeDelta)
     (prop_timedelta id_bwHost id_bxTimeDelta)
     (prop_timedelta id_cdHost id_ceTimeDelta)
     (prop_timedelta id_ckHost id_clTimeDelta)
     (prop_timedelta id_crHost id_csTimeDelta)
     (prop_timedelta id_cyHost id_czTimeDelta)
     (prop_timedelta id_dfHost id_dgTimeDelta)
     (prop_timedelta id_gHost id_hTimeDelta)
     (prop_timedelta id_nHost id_oTimeDelta)
     (prop_timedelta id_uHost id_vTimeDelta)
     (prop_user id_dDomainCredential id_cDomainUser)
     (prop_username id_cDomainUser str__james)
     (prop_windows_domain id_aDomain str__alpha)
)
(:goal   (and 
     (prop_host id_esRat id_uHost)
     (prop_host id_ewRat id_bbHost)
     (prop_host id_epRat id_nHost)
     (prop_host id_eqRat id_dfHost)
     (prop_host id_emRat id_bpHost)
     (prop_host id_eoRat id_cdHost)
     (prop_host id_enRat id_biHost)
     (prop_host id_evRat id_crHost)
     (prop_host id_etRat id_cyHost)
     (prop_host id_euRat id_bwHost)
     (prop_host id_erRat id_gHost)
)
)
)